### ISSUE TITLE
Angular.js

### ISSUE THREAD

**Issue by njss** [syntagmatic/parallel-coordinates#278]
I cannot make the parcoord work with angular.js...
No idea what is happening, the svg is always width=0 and height =0...
Is there any angular.js example?

**Comment by bbroeksema** [comment]
Not a simple example because it's a pretty complex application on its own, but you could have a look here: https://github.com/bbroeksema/ICoVeR/tree/master/R.ICoVeR/inst/www/.

It will require a bit of digging to see how I got things working, but at least shows that it's possible to use parcoords in combination with angular.

**Comment by dehli** [comment]
@njss Can you post a [JSFiddle](jsfiddle.net) of it not working?

**Comment by dehli** [comment]
I'm going to go ahead and close this due to its inactivity.
