### ISSUE TITLE
Graphs are not showing. CSV issue? 

### ISSUE THREAD

**Issue by newbie1224** [syntagmatic/parallel-coordinates#329]
So my code is set up correctly (using Eclipse) as far as I can understand. However when I run the html files my graphs are non-existent and do not show in the browser (Chrome). The graphs show fine when I interact with the posted example graphs on the main site (http://syntagmatic.github.io/parallel-coordinates/). However, when I try to run them, I get the following which is depicted in the picture. 
![image](https://cloud.githubusercontent.com/assets/23134617/19828311/70e2d070-9d77-11e6-854c-49a625c08ed4.png)

The html files that do not need to read any data from a file (CSV) seem to work perfectly. Since brushing.html needs cars.csv, it is failing. What is the error? 
Any idea what's going on here??? It is frustrating. Maybe the solution is simple but I am open to hear suggestion.

**Comment by syntagmatic** [comment]
Hi @newbie1224! Thanks for posting a screenshot of the page, I can tell exactly what's happening.

The issue is a web page can't just load files off your local computer. It would be a security risk if they could: malicious websites would be able to scrape personal data off your machine.

To view the examples, you need to run a web server in the `parallel-coordinates-master` directory you've created. Then you should be able to load the example at the URL http://localhost:8000/examples/brushing.html or something like that.

Any web server should work, just find something easy to set up. WAMP, Python's SimpleHTTPServer and `npm serve` are three options.

**Comment by newbie1224** [comment]
Thank you so much!!!! It's working now. It would've taken me forever to figure that out. :)
