### ISSUE TITLE
Display ordinal dimensions with a single value domain/range

### ISSUE THREAD

**Issue by shodanjr** [syntagmatic/parallel-coordinates#88]
I came across the following issue with a PC chart which is embedded into a larger application with data filtering functionality. Specifically, my data would contain an ordinal dimension which, depending on the active filter, would contain only a single value across the entire domain. When that happened, the axis associated with that particular dimension ended up getting removed completely from the chart. 

I traced this down to pc.autoscale and specifically the following bit:

```javascript
pc.dimensions(pc.dimensions().filter(function(p,i) {
    var uniques = yscale[p].domain().length;
    if (__.types[p] == "string" && (uniques > 60 || uniques < 2)) {
      return false;
    }
    return true;
  }));
```
The ```uniques < 2``` option will throw away any ordinal dimension that only contains one unique value. I can see situations where this is desirable but I can also see several use cases where this might not be appropriate behavior (for example, in an interactive chart with filtering, this would constantly change the visual appearance and have the axes shift around). 

To me it would make sense for this kind of behavior to be determined by a flag. For my use-case, simply changing the line to read ```uniques < 1``` works.

I'd rather have some discussion on expected behaviors before contributing a fix :).

**Comment by syntagmatic** [comment]
For a single unique value, adjusting the behavior of #79 would be desirable.

`uniques > 60` is also a hack, to prevent labels from crowding each other. But if some ordinal labels were skipped so that only ~20-30 labels showed up, there would be no problem with including a scale with many values in the domain.

Two flags for the min/max number of uniques sounds find to me. I've left this hack in there for a long time so that the chart would render decently in common cases, but I sometimes trip over edge cases as well and edit the line manually. It needs to go.

**Comment by shodanjr** [comment]
If I skip the check, then i actually get the optimal behavior that you describe in #79 (label in the middle of the axis range, poly line crossing through it). I don't like the idea of skipping labels in an ordinal dimension, especially since the library does not (yet) support hovering over polylines to get the actual values. I'll look into implementing an API for setting the minimum/maximum number of uniques, hopefully in the next few days.

**Comment by syntagmatic** [comment]
Awesome work. This is an important detail.

**Comment by syntagmatic** [comment]
https://github.com/syntagmatic/parallel-coordinates/commit/b41670cdadeca39e875111d4c77fae07c041a1c8
